[package]
name = "bedrockrs_proto_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bedrockrs_macros = { path = "../macros" }

nbtx = { git = "https://github.com/bedrock-crustaceans/nbtx" }
xuid = "1.0"

paste = "1.0"
seq-macro = "0.3"

byteorder = "1.5"
varint-rs = "2.2"

vek = "0.17"
thiserror = "2.0"

serde_json = "1.0"
jsonwebtoken = "9.3"
base64 = "0.22"
uuid = { version = "1.11", features = ["v4"] }
